on: 
  push:
    branches: [master]
    
name: sync ftp files
jobs:
  web-deploy:
    name: git file sync on branch update
    runs-on: ubuntu-latest
    steps:
    - name: fetch latest files
      uses: actions/checkout@v3
    
    - name: send latest files
      uses: sand4rt/ftp-deployer@v1.7
      with:
        sftp: true
        host: ${{ secrets.ftp_server }}
        port: ${{ secrets.ftp_port }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local_folder: data/ttt/maps/
        remote_folder: garrysmod/data/ttt/maps/
        
